Format Output
Piston-CLI/piston-cli pull request #10
Opened 2021-02-16 08:21 UTC by Shivansh-007

Add format output helper function and if output more than 2000 chars or 20 lines then send to emkc snippets.

**Upload output to emkc snippet**

![Screenshot from 2021-02-16 13-45-16](https://user-images.githubusercontent.com/69356296/108036150-dd2e4a80-705d-11eb-8f19-7092dbcc4a16.png)

**Too long to upload to emkc snippets**

![Screenshot from 2021-02-16 13-37-37](https://user-images.githubusercontent.com/69356296/108036154-de5f7780-705d-11eb-92f2-decccf9eaad3.png)

2021-02-16 15:50 UTC, SuperMaZingCoder requested changes

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +MAX_CHARACTERS = 2000
Should these be moved to `constants.py`?

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +    output = output.rstrip("\n")
This should be `output = output.strip()`

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        output = [f"{i:03d} | {line}" for i, line in enumerate(output.split("\n"), 1)]
This should be `{i:02d}` because the max line length is less than a three digit number.

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +def format_output(output: str) -> Tuple[str, Optional[str]]:
The `output` arg is a list, not a string.

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        output = output[:MAX_LINES]  # Limiting to only 20 lines
This should come before the line above this one:
```py
output = output[:MAX_LINES]  # Limiting to only 20 lines
output = [f"{i:03d} | {line}" for i, line in enumerate(output.split("\n"), 1)]
```

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        output = output[:MAX_LINES]  # Limiting to only 20 lines
Or, if not that, this should be moved inside of the `if lines > MAX_LINES:` block.

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +            )
This should be moved to the if statement: 
```py
if lines > MAX_LINES or len(output) >= MAX_CHARATERS:
```
This way, one line that is thousands of characters long is truncated too. And then, set output to:
```py
output = (
    f"{output[:MAX_CHARACTERS]}\n... (truncated - too long or too many lines)"
)
```

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +            output = f"{output}\n... (truncated - too many lines)"
See above comment.

2021-02-16 15:50 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +            output = f"{output}\n... (truncated - too many lines)"
ah nevermind, saw below

2021-02-16 15:51 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +            )
nevermind, saw below

2021-02-17 01:41 UTC, Shivansh-007 commented on piston/utilities/format_output.py
> +        output = output[:MAX_LINES]  # Limiting to only 20 lines
We can't move it before since it is a string, and while adding numbers it gets converted to a list.

2021-02-17 01:43 UTC, Shivansh-007 commented on piston/utilities/format_output.py
> +        output = output[:MAX_LINES]  # Limiting to only 20 lines
And no for the second as we have two cases to check and just doing it one place and excluding one check to be done twice is faster.
You can have a look at the `eval` command of pydis/bot, It has been implemented with the help of that.

2021-02-17 05:37 UTC, Shivansh-007 commented
Have a few merge conflicts and need to implement this in the `from_shell.py` will do that :)

2021-02-17 15:12 UTC, SuperMaZingCoder requested changes

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/commands/fromfile.py
> +            return result, language
This could probably be one line, though, I'm not sure how that would affect readability.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/commands/frominput.py
> +            return result, language
This could probably be one line, though, I'm not sure how that would affect readability.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/commands/fromlink.py
> +            return result, language
This could probably be one line, though, I'm not sure how that would affect readability.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> +    MAX_CHARACTERS = 2000
To stay consistent with the FromShell class, this should be lowercased. This is also how the pydis repos do it for reference.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> +class FormatOutput(NamedTuple):
This shouldn't be a `typing.NamedTuple`. On the [documentation](https://docs.python.org/3/library/typing.html#typing.NamedTuple), it specifies usage for named tuples as:
```py
class Employee(NamedTuple):
    name: str
    id: int
```
Don't inherit from anything here.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +    original_output = output  # To be uploaded to a pasting service if needed
Save original output before stripping it, as that would modify it, even if only slightly.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        output = output[: FormatOutput.MAX_LINES]
Remove the spacing here.

2021-02-17 15:12 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        msg = f"{msg}\nFull output: {paste_link}"
We should add an `else` statement to indicate somewhere that pasting failed rather than skipping it entirely.

2021-02-17 15:18 UTC, Shivansh-007 commented on piston/utilities/format_output.py
> +        output = output[: FormatOutput.MAX_LINES]
Black does that.

2021-02-17 15:19 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +        output = output[: FormatOutput.MAX_LINES]
ah, okay, you can resolve this in that case, though, it does look a bit weird.

2021-02-18 08:51 UTC, Shivansh-007 commented
Mentioned the required changes @SuperMaZingCoder!

2021-02-18 15:05 UTC, SuperMaZingCoder requested changes

2021-02-18 15:05 UTC, SuperMaZingCoder commented on piston/utilities/constants.py
> +    max_characters = 2000
These should go after the "core constants", that way they will be in the same position as the FromShell constant class.

2021-02-18 15:05 UTC, SuperMaZingCoder commented on piston/utilities/format_output.py
> +            return f"[Pasting failed with status code {status}... Try again later.]"
This should go outside of the for loop, as right now this ignores the looping altogether. You can just remove the return statement to the end and it will be fine, because if it was successful it will have returned already.

2021-03-15 23:58 UTC, Shivansh-007 commented on piston/utilities/format_output.py
> +            return "https://emkc.org" + response["url"]
Move the paste service to hastebin.com instead of emkc snippets.

To note, currently paste.pythondiscord.com is the only link allowed in `--link` flag, expand this list, make it configurable with probable options as: (To be mentioned in a separate PR).

- pastebin.com
- hastenin.com 
- paste.pythondiscord.com

2021-03-18 04:58 UTC, Shivansh-007 commented on piston/utilities/format_output.py
> +            return "https://emkc.org" + response["url"]
I can mentioned the above change, after #16 gets merged!

2021-05-09 16:45 UTC, Shivansh-007 commented
I will be closing this PR, as we have decided not to implement this, we should keep all the output within the shell, so the user doesn’t have to leave it.

Secondly if someone writes some code to output something huge, the end lines aren’t really needed, say a `while True:print("Hello, World!")`. So they can scroll to the bottom any ways.

2021-05-09 16:45 UTC, closed without merging