Verson 1.4.0
Piston-CLI/piston-cli pull request #43
Opened 2021-04-18 15:40 UTC by Shivansh-007

## Relevant Issues
Closes #21 #22 #40 #42

## Description
This is a big PR, and brings a number of changes, should have broken into separate PRs, but I was too lazy to do that. Here is a summary of all the changes:

- We had a lot of similar code in many places, a number of values with same purpose being defined at a number of places, I went ahead and wrote helper functions for these, so it can be easy to edit the code from one place rather than going to every instance. This also moves all the constants to `constants.py`.
- Makes `-T` `--themelist` more better and informative, but showing a short snippet of each theme, so that a user can choose and differentiate between the themes in a better way.
- Enhances `sys.stdin` and `sys.argv` parsing:
    * Originally we were splitting the inputs or commas `,`, and hence one couldn't pass that into the input when they would require it. 
    * Then i came up with the idea to make this split configurable, but nah, this would be a pain in the ass for the users, change it every time they would require the character and sometimes even forgot it
    * Finally came the best option, make it like python string parser, each input would be contained inside quotes, double/single, and once can escape it with the help of backslash `\`.
    * Example: `"hello" "this" "is" "jason\"s super cat"` would be change to `"hello this is jason"s super cat"`
- There was a small bug in the config pr #16, 🤦🏻‍♂️ bad reviewing, when a user specified the theme with `-t` flag, it wouldn't consider that and would take the theme specified in the `config.yml`. This PR fixes this change and also informs the user in case there is a over-writing of the theme when they specify the theme with `-t` flag.
- Configures flake8 to know which are local imports, so that they can be put into a new line.
- Having a plane box around the code output, sounds boring? Yes, atleast for me, now we can configure it in `config.yml`, with `box_style` key, this style would then be used to print the code output.

## Screenshots

To Do...

## Did you:

- [x] Join the [**Piston CLI Discord Community**](https://discord.gg/c7dZ4zdGQT)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?

2021-04-24 17:27 UTC, SuperMaZingCoder requested changes
A review to start with. I'll continue looking through and add more changes in a separate review as I need to.

2021-04-24 17:27 UTC, SuperMaZingCoder commented on piston/utils/maketable.py
>          for lang in cont:
If this is a util method, should we make it more versatile than it's only purpose to display the available languages?

2021-04-24 17:27 UTC, SuperMaZingCoder commented on piston/utils/maketable.py
>          for lang in cont:
Especially considering that this only has one usage, it may  not even fit into the intent of a "util".

2021-04-24 17:27 UTC, SuperMaZingCoder commented on piston/utils/theme_preview.py
> +    return f"The square of {num:.2} is {result:.2}."
Not specifically related to this, but if we are using `utils` more generally, we should start sorting its contents into folders.

2021-04-24 17:27 UTC, SuperMaZingCoder commented on piston/version.py
> +import tomlkit
Remember that we need to add this dependency.

2021-04-24 17:27 UTC, SuperMaZingCoder commented on piston/version.py
> +    return str(tomlkit.parse(file_contents)["tool"]["poetry"]["version"])
Perhaps the version should be a constant, `__version__` in `piston/__init__.py` that we update with each release. This code seems a bit round-a-bout.

2021-04-24 23:31 UTC, Shivansh-007 commented
This method is being used for making languages tables too, I will update this and make it more flexible.

2021-04-24 23:38 UTC, Shivansh-007 commented on piston/version.py
> +import tomlkit
This dependency is added in the `pyproject.toml`, I am not sure on why you get `ModuleNotFoundError: No module named 'tomlkit'`, I will see if I can replicate the error on mine.

2021-04-24 23:40 UTC, Shivansh-007 commented on piston/version.py
> +    return str(tomlkit.parse(file_contents)["tool"]["poetry"]["version"])
We could do that, but then I thought we would be defining it at two places, so if we have a method to make it one, why not do it?

If we are not able solve the 'tomlkit' problem, we make this a constant.

2021-04-24 23:41 UTC, Shivansh-007 commented on piston/utils/maketable.py
>          for lang in cont:
I will make it more flexible.

2021-04-24 23:42 UTC, Shivansh-007 commented on piston/__init__.py
> +    if args.version:
> Update: I'm getting this whenever I attempt to use any piston-cli flag at all.

This same error?

2021-04-25 00:13 UTC, SuperMaZingCoder commented on piston/__init__.py
> +    if args.version:
> > Update: I'm getting this whenever I attempt to use any piston-cli flag at all.
> 
> This same error?

Yep, I tried again each flag and received the same error.

2021-04-25 00:13 UTC, SuperMaZingCoder commented on piston/utils/maketable.py
>          for lang in cont:
Sounds good!

2021-04-25 00:13 UTC, SuperMaZingCoder commented on piston/version.py
> +import tomlkit
Strange.. perhaps it had to do with the way I installed the dependencies? Via `python3 -m pipenv install --dev`

2021-04-25 00:17 UTC, SuperMaZingCoder commented on piston/version.py
> +    return str(tomlkit.parse(file_contents)["tool"]["poetry"]["version"])
> We could do that, but then I thought we would be defining it at two places, so if we have a method to make it one, why not do it?
> 
> If we are not able solve the 'tomlkit' problem, we make this a constant.

I think I've seen other projects which have a version specified in `setup.py` and a version in `__init__.py`. It's up to you, but personally, this seems like extra code that could be avoided easily. 

The other benefit to this is that once it's installed, anyone using this can have an easier time viewing the version (assuming they are working with the code) using `import piston` and then `piston.__version__`. This is more convenient and makes more sense than a having a module just for retrieving the version from `pyproject.toml` imo.

2021-04-25 00:18 UTC, Shivansh-007 commented on piston/version.py
> +import tomlkit
We have moved away from pipenv 🙃, and yeah let me see if that’s possible.

2021-04-25 00:20 UTC, Shivansh-007 commented on piston/version.py
> +    return str(tomlkit.parse(file_contents)["tool"]["poetry"]["version"])
Agreed, I will revert those changes back.

2021-04-25 00:50 UTC, SuperMaZingCoder commented
I think we should also document the available box styles. The two options are:

1. Add a command for listing the choices of box styles (probably involves changing the functionality of `-T` and `--list` to a modified `--list` command which takes a string that specifies *what* to list, e.g. `--list themes`, `--list languages`, `--list boxes`)
2. Write a wiki entry about configurable options and include it (probably involves removing the `-T` flag in favor of putting all of the options for configs into the wiki).

2021-04-25 00:56 UTC, SuperMaZingCoder commented on piston/commands/base.py
>              "-list",
Singular `-` should be used with one letter only, e.g. `-i`, this is because `-`'s are used to chain flags. For example, `-vf` is equivalent to `-v -f`. Using a single dash will likely break functionality.

2021-04-25 01:01 UTC, Shivansh-007 commented
> I think we should also document the available box styles. The two options are:
> 
> 1. Add a command for listing the choices of box styles (probably involves changing the functionality of `-T` and `--list` to a modified `--list` command which takes a string that specifies _what_ to list, e.g. `--list themes`, `--list languages`, `--list boxes`)
> 2. Write a wiki entry about configurable options and include it (probably involves removing the `-T` flag in favor of putting all of the options for configs into the wiki).

That is a good idea, I will go ahead and implement the 1st method, secondly for the 2nd method imo we could try using the GitHub wiki tool rather.

2021-04-25 01:02 UTC, SuperMaZingCoder commented
> That is a good idea, I will go ahead and implement the 1st method, secondly for the 2nd method imo we could try using the GitHub wiki tool rather.

Sounds good, that's also what I meant when I said wiki before, haha. And yeah, I think we could/should start working on the wiki sometime soon.

2021-05-21 06:33 UTC, Shivansh-007 commented on .flake8
> +        media
Media has now been moved to a separate repo, so this isn't needed anymore.

2021-05-21 06:33 UTC, Shivansh-007 commented on piston/__init__.py
> +            )
Add comments explaining the `try..else` and `isinstance` block for easier understanding.

2021-05-21 06:33 UTC, Shivansh-007 commented on piston/__main__.py
>          print(f"Error: \n{e}")
Add `--debug` flag which will display the full error rather than handling it here.

2021-05-21 06:33 UTC, Shivansh-007 commented on piston/commands/from_file.py
> +from typing import Tuple
As we are using `python3.9` on the package, this can be moved to `tuple[...]`

2021-05-21 06:33 UTC, Shivansh-007 commented on piston/commands/theme_list.py
> +        CONSOLE.print(f"[b red u]Theme {theme}: [/b red u]\n")
Use full style names for consistency

2021-05-24 04:44 UTC, merged