Feature: Make prompt in shell mode configurable
Piston-CLI/piston-cli pull request #56
Opened 2021-05-23 02:25 UTC by SatvikR

## Relevant Issues

Closes #54 

## Description

This pr adds two new fields to the configuration file: `prompt_start` and `prompt_continuation`.
If a custom prompt has a new line (`\n` or `\r`) in it, it is invalidated.

## Reasoning

I mainly followed a similar approach to the theme configuration when writing this feature,

## Screenshots

Example config file:
![image](https://user-images.githubusercontent.com/49799352/119246070-1c73a800-bb33-11eb-8a38-e8262b3baef8.png)

How it looks on the user side:
![image](https://user-images.githubusercontent.com/49799352/119246084-4e850a00-bb33-11eb-85cd-3cb1cd2a998b.png)

## Did you:

- [x] Join the [**Piston CLI Discord Community**](https://discord.gg/c7dZ4zdGQT)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-05-23 02:30 UTC, Shivansh-007 commented
I will wait for #43 to get merged and then merge this.

2021-05-24 08:08 UTC, Shivansh-007 commented
Hey @SatvikR can you resolve the merge conflicts?

2021-05-24 08:43 UTC, SatvikR commented
> Hey @SatvikR can you resolve the merge conflicts?

Sure @Shivansh-007, I can fix them later today.

2021-05-25 03:50 UTC, Shivansh-007 requested changes
Looks like when you used the github button to merge the conflicts, it didn't get them right, and the `piston/utils/lexers.py` now has some of the constants/

2021-05-25 03:50 UTC, Shivansh-007 commented on piston/__init__.py
> +                config["theme"] or args.theme,
```suggestion
                args.theme or config["theme"],
```

2021-05-25 03:50 UTC, Shivansh-007 commented on piston/configuration/config_fixer.py
>      config["box_style"] = BoxStyleValidator(config["box_style"]).fix_box_style()
Group it according to the config category.

```suggestion
    config["theme"] = ThemeValidator(config["theme"]).fix_theme()
    config["box_style"] = BoxStyleValidator(config["box_style"]).fix_box_style()

    config["prompt_start"] = PromptStartValidator(config["prompt_start"]).fix_prompt()
    config["prompt_continuation"] = PromptContinuationValidator(
        config["prompt_continuation"]
    ).fix_prompt()
```

2021-05-25 03:50 UTC, Shivansh-007 commented on piston/configuration/validators/prompt_validator.py
> +        return self.default_prompt
The user doesn't get to know why it chooses the default prompt and not the one it specified in the `config.yml`. Might want to print a error in `red` here. Similarly for `PromptContinuationValidator`

This is how it is done for box style validator

![Screenshot from 2021-05-25 09-19-19](https://user-images.githubusercontent.com/69356296/119436725-5f539c80-bd3a-11eb-89af-2b52aa221f29.png)

2021-05-25 04:16 UTC, SatvikR commented on piston/configuration/validators/prompt_validator.py
> +        return self.default_prompt
I'm having it print this now, let me know if I should change it
![image](https://user-images.githubusercontent.com/49799352/119438505-351bc380-bcd5-11eb-82fd-d92a7597ba68.png)

2021-05-25 04:34 UTC, Shivansh-007 commented on piston/configuration/validators/prompt_validator.py
> +                line character. Using default prompt start instead.[/red]"""
- Personal preference, but I don't like the use `/` here, you can just break it into two strings and python automatically connects them into one.
- Say your `prompt_start` is `>>\n>` then it would be displayed with the newline in the error, a way to escape this is to use `repr()`

This is how the above looks

![Screenshot from 2021-05-25 10-03-28](https://user-images.githubusercontent.com/69356296/119439689-83b27780-bd40-11eb-8204-a629c45892a2.png)


```suggestion
            f"[red]Prompt start invalid. {repr(self.prompt)} contains a new"
            "line character. Using default prompt start instead.[/red]"
```

Do the same on `PromptContinuationValidator`

2021-05-25 04:34 UTC, Shivansh-007 commented
Looks you committed some debug code in `piston/__main__.py`

2021-05-25 04:36 UTC, SatvikR commented
> Looks you committed some debug code in `piston/__main__.py`

Sorry about that, should be fixed now

2021-05-25 04:37 UTC, Shivansh-007 commented
No Worries!

2021-05-25 05:02 UTC, Shivansh-007 approved these changes
Looks good!

2021-05-25 05:03 UTC, merged