Prevent keyboard interrupt errors
Piston-CLI/piston-cli pull request #61
Opened 2021-05-26 08:53 UTC by pranavbaburaj

- Prevent inputs from capturing keyboard interrupts.
- Replaced `try..except` block with `os.path.isfile(filename)` for validating files

 - [x] Join the Piston CLI Discord Community?
 - [x] If dependencies have been added or updated, run pipenv lock?
 - [x] Lint your code (pipenv run lint)?
 - [ ] Set the PR to allow edits from contributors?

2021-05-26 09:01 UTC, pranavbaburaj commented
Closes #62

2021-05-26 10:02 UTC, Shivansh-007 requested changes
Two comments here,

1. Firstly you need to open a issue first, get it approved and assigned, then you can start working on the issue. Sometimes we don't approve issues so your PR could go waste.

2. Secondly, I am not 100% convinced with this solution, I had rather have it [`piston/__main__.py`](https://github.com/Piston-CLI/piston-cli/blob/main/piston/__main__.py). So that it handles all the errors together, it isn't "pythonic" to go put a `try..except` everywhere this can happen (there are few places where this still occurs, like the code input in `from_input.py`)

2021-05-26 10:17 UTC, Shivansh-007 commented
Better commit messages please.

A in-depth guide to writing great commit messages can be found in Chris Beam's [_How to Write a Git Commit Message_](https://chris.beams.io/posts/git-commit/).

2021-05-26 10:18 UTC, pranavbaburaj commented
> Better commit messages please. (pointing to [d37063e](https://github.com/Piston-CLI/piston-cli/commit/d37063e72fc2a18611c495af35ce2b70858e97da))
> 
> A in-depth guide to writing great commit messages can be found in Chris Beam's [_How to Write a Git Commit Message_](https://chris.beams.io/posts/git-commit/).

I am sorry for that 😐

2021-05-27 13:57 UTC, pranavbaburaj commented on piston/utils/helpers.py
> +
This is the function that handles the input

2021-05-27 14:01 UTC, closed without merging